### PR TITLE
Add Calculator class for basic operations.

### PR DESCRIPTION
**Pull request by safi-io**

### CODE REVIEW

**Comment by hashamyounis9** [comment]
even though this code works fine, there is room for small design improvement, rather than all the functions printing the operation being done, they should just perform the operation and return the result, then print it in the  main function or maybe create a new function to print in a nice formatted way, this function takes both numbers, operation performed, and result as parameter and displays it on the standard output.

**Comment by safi-io** [comment]
Can you guide me how to target the issue? @hashamyounis9

**Comment by hashamyounis9** [comment]
You can target using "#issue no" in our particular case it will be #6

**Comment by safi-io** [comment]
I have done all the work, Kindly check it out. This PR fixes the #6 .

**Comment by hashamyounis9** [comment]
in the `division` method in class `Calculator`, user may enter 0 as num2 which will cause the app to crash, please handle this case inside `division` method, or ask user to enter a non-zero while taking input from user before passing to the function

@safi-io

**Pull request merged**
